# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages

author:
  name:       Данил Степанов
  url:        https://ms-ware.ru 

lang: ru-RU
encoding: utf-8
permalink: pretty
highlighter: rouge
markdown: kramdown